apiVersion: v1
kind: Service
metadata: 
  name: k8s-api
  namespace: test
  labels:
    app: k8s-api
spec: 
  ports:
    - name: k8s-api
      port: 5006
      nodePort: 30434
  type: NodePort
  selector:
    app: k8s-api
