apiVersion: v1
kind: Service
metadata:
  name:  k8s-gateway
  namespace: test
spec:
  selector:
    app:  k8s-gateway
  type:  ClusterIP
  ports:
  - name:  k8s-gateway
    port:  5007
    targetPort:  5007